### ISSUE TITLE
Lightbox issue umbrella

### ISSUE THREAD

**Issue by gaearon** [bluesky-social/social-app#1473]
I'm filing this to keep track of various things that are broken / not ideal / weird with our lightbox. Some may already have issues filed, others don't (yet).

- [ ] Backend
  - [ ] https://github.com/bluesky-social/social-app/issues/1101
    - We should strip out the metadata but we should never upscale user-submitted images
- [ ] Gestures
  - [x] Double tap to zoom
    - [x] https://github.com/bluesky-social/social-app/issues/1275 
      - [x] Fix it on Android
      - [x] Align iOS behavior with the Android fix
    - [x] Double tap doesn't work in the header area (even to the left of the close button)
      - [x] Fix: https://github.com/bluesky-social/social-app/pull/1489
  - [ ] Pinch
    - [x] https://github.com/bluesky-social/social-app/issues/1485 
    - [x] Images in a single post may end up overlapping on Android
    - [x] Make it resistant to gesture spam
  - [ ] Swipe
    - [ ] Swiping sometimes gets stuck
    - [ ] Black screen feels weird
    - [ ] There's sometimes a spinner behind an already loaded image
-  [ ] Alt text 
    - [ ] https://github.com/bluesky-social/social-app/issues/1265
      - This needs some design consideration. Maybe hide on tap.
    - [ ] https://github.com/bluesky-social/social-app/issues/1445
      - The original issue is about web but we probably we want fix it across.
- [ ] Perf
  - [ ] Takes too long to open lightbox on Android
  - [x] Look into allocations
  - [x] Look into parent callback spamming

**Comment by gaearon** [comment]
I'm rolling this into a bigger https://github.com/bluesky-social/social-app/issues/1675.
