### ISSUE TITLE
Quality umbrella

### ISSUE THREAD

**Issue by gaearon** [bluesky-social/social-app#1675]
I'll keep track of some things that are bugging me here.

This is an incomplete list, I'll keep adding stuff here.

- [ ] Shell
  - [x] First load
    - [x] Flicker of white https://github.com/bluesky-social/social-app/pull/1759
    - [x] Feed jumps around sometimes
    - [x] Profile picture in the tab bar disappearing and reappearing during init
  - [x] Glimmer after flicking a feed is missing top margin
  - [x] Top/bottom bar disappearance feels a bit janky
    - [x] https://github.com/bluesky-social/social-app/pull/1683
    - [x] https://github.com/bluesky-social/social-app/pull/1691
    - [x] The content should “push” the bar up, synchronized with the gesture https://github.com/bluesky-social/social-app/pull/1855
    - [x] It's also weird when we're already at the top and just scroll down and up a bit — causes blank space https://github.com/bluesky-social/social-app/pull/1855
    - [x] Switching between feeds while the bar is hidden feels janky due to blank space https://github.com/bluesky-social/social-app/pull/1856
  - [x] Gesture hell
    - [x] Swipe between custom feeds with little distance is interpreted as tap on Android
    - [x] Swipe between custom feeds on the left side is interpreted as a drawer swipe on Android
  - [x] The feed switching header animation should be synchronized with the swipe gesture
  - [x] Navigating to a profile not via preview (e.g. via link click) is missing a push animation
  - [x] There is no fade on the background view during back gesture
  - [ ] There is no header crossfade during back gesture
- [x] Feed
  - [x] Feed items
    - [x] Layout shift due to galleries https://github.com/bluesky-social/social-app/pull/1673
    - [x] Layout shift when there's a link attachment
    - [x] Tapping a feed item makes the parent post spinner too visible (need to shift it)
    - [x] Tapping a reply may cause a content jump just before it scrolls to reply
    - [x] Button positions in the glimmer are too off
    - [x] Pressing like shouldn't move other buttons
    - [x] Back gesture feels unreliable when starting with a long press and then a quick swipe; often interprets as tap
    - [x] There's no tap target feedback e.g. on counts
    - [x] We're loading too many too large images
      - [x] Don't upscale images https://github.com/bluesky-social/social-app/issues/1101
      - [x] Load small avatars by default
    - [x] "In reply to" should be resolved with initial payload
    - [x] Clicking a post in a thread on the web is jumpy
    - [x] Clicking on a post should never show spinner for that post’s content 
  - [x] Profile preview
    - [x] Blank background while animating looks broken on Android
    - [x] There is a jump after navigating on iOS due to safe area https://github.com/bluesky-social/social-app/pull/1693
    - [x] There is a flash because the modal disappears before the navigation commits https://github.com/bluesky-social/social-app/pull/1693
    - [x] The initial state is empty but we should have enough info to show the profile shell immediately 
    - [x] The display name while loading is misaligned https://github.com/bluesky-social/social-app/pull/1693
  - [x] Lightbox
    - [x] Opening lightbox is laggy / misses target on Android (interferes with showing/hiding chrome?)
    - [x] There's no transition between the thumb and the lightbox image and back
    - [x] Lightbox doesn't take advantage of the already loaded thumb image (should it?)
    - [x] Gestures
      - [x] Double tap to zoom
        - [x] https://github.com/bluesky-social/social-app/issues/1275 
          - [x] Fix it on Android
          - [x] Align iOS behavior with the Android fix
        - [x] Double tap doesn't work in the header area (even to the left of the close button)
          - [x] Fix: https://github.com/bluesky-social/social-app/pull/1489
      - [x] Pinch
        - [x] https://github.com/bluesky-social/social-app/issues/1485 
        - [x] Images in a single post may end up overlapping on Android https://github.com/bluesky-social/social-app/pull/1624
        - [x] Make it resistant to gesture spam https://github.com/bluesky-social/social-app/pull/1666
        - [x] The controls flying away animation is too aggressive https://github.com/bluesky-social/social-app/pull/1687
      - [x] Swipe
        - [x] Swiping sometimes gets stuck
        - [x] Hide alt text during swipe?
        - [x] Black screen feels weird
        - [x] There's sometimes a spinner behind an already loaded image
    -  [x] Alt text 
        - [x] Implement "hide on tap" https://github.com/bluesky-social/social-app/pull/1687
        - [x] https://github.com/bluesky-social/social-app/issues/1445
- [x] Notifications
  - [x] Pressing the notification icon doesn't do the refresh animation properly
  - [x] Pressing notifications icon second time should clear it 
  - [x] Layout is borked when people joined with your invite
- [x] Profile
  - [x] First profile load jumps https://github.com/bluesky-social/social-app/pull/1690
- [x] Composer
  - [x] Cropping needs rethinking on the web

**Comment by mozzius** [comment]
>Pressing the notification icon doesn't do the refresh animation properly

For whatever reason, you can't declaratively show the platform refresh animation - hence the fake spinner. Even if you can't use the platform animation, It'd probably look significantly better if you added Reanimated layout animations so that it didn't jump open/closed

Worth noting twitter shows no animation, and threads shows a spinner in the header, top right - I've yet to find an instance where an app opens the pull-to-refresh thing by pressing a different button.

**Comment by gaearon** [comment]
Makes sense. Not saying it needs to animate in particular but something feels janky about it. I guess maybe not showing the spinner (like twitter does) may be better.

**Comment by mackuba** [comment]
@gaearon hey, I finally managed to catch the "jumping up and down when scrolling far down a list" effect that I mentioned recently - I saw this while scrolling on my own profile for posts >1 month ago: https://files.mastodon.social/media_attachments/files/111/371/299/920/026/645/original/29aaba275b20302d.mp4 (starts around ~0:20)
Safari 17.1, macOS 12.7.1

**Comment by gaearon** [comment]
Very interesting, thanks!

**Comment by velosol** [comment]
I'm not quite sure where to broach this but I wanted to suggest an enhancement to Lightbox gestures on Android to support "doubletap with swipe"* to mimic pinch to zoom. It's a long-standing and one-handed accessible zoom option that I think would be nice when viewing images.

*: https://www.youtube.com/watch?v=6Y7nPhk18W0 (not my video but shows the gesture)

**Comment by gaearon** [comment]
I think we can close this. It's close enough
